name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy_and_create_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to gh-pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git branch -a  # Optional: Display branches for debugging purposes
          git checkout gh-pages || git checkout --orphan gh-pages
          cp -r docs/* ./
          touch .nojekyll
          git add .
          git commit -m 'Update gh-pages'
          git push origin gh-pages -f